[package]
name = "integer-digits-sum"
version = "0.1.0"
authors = ["MuhammadNaeemAkhtar <mnakhtar247@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
